// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BE6u9vbhb3tJmOvSDIPfpQN6oKhtdww',
    appId: '1:1049527709192:web:cd0420117e49b4c2e6abbd',
    messagingSenderId: '1049527709192',
    projectId: 'our-school-de45e',
    authDomain: 'our-school-de45e.firebaseapp.com',
    storageBucket: 'our-school-de45e.firebasestorage.app',
    measurementId: 'G-F5BP6TWPWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvOuPPU3HYXsP95QsyccwwEtM-djEfdPU',
    appId: '1:1049527709192:android:e0ab540b922d23e8e6abbd',
    messagingSenderId: '1049527709192',
    projectId: 'our-school-de45e',
    storageBucket: 'our-school-de45e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00bAhEBBdAxeKnBA8oNQ7z3cmuzW7HH4',
    appId: '1:1049527709192:ios:0ac2e9ef48005b48e6abbd',
    messagingSenderId: '1049527709192',
    projectId: 'our-school-de45e',
    storageBucket: 'our-school-de45e.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00bAhEBBdAxeKnBA8oNQ7z3cmuzW7HH4',
    appId: '1:1049527709192:ios:0ac2e9ef48005b48e6abbd',
    messagingSenderId: '1049527709192',
    projectId: 'our-school-de45e',
    storageBucket: 'our-school-de45e.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2BE6u9vbhb3tJmOvSDIPfpQN6oKhtdww',
    appId: '1:1049527709192:web:c21fec898e6948b5e6abbd',
    messagingSenderId: '1049527709192',
    projectId: 'our-school-de45e',
    authDomain: 'our-school-de45e.firebaseapp.com',
    storageBucket: 'our-school-de45e.firebasestorage.app',
    measurementId: 'G-C3T1CZGGN0',
  );
}
